version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - 4000:4000
    volumes:
      - ./types:/types
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./types:/types
